'use client';
import {createContext,useContext,useEffect,useRef,useState,useCallback} from 'react';
import {usePathname} from '@/lib/navigation';
const SoundContext=createContext({playing:false,toggle:()=>{},start:async()=>{},cue:(_kind:'select'|'settle')=>{}});
export function useSound(){return useContext(SoundContext)}
export function Immersion({children}:{children:React.ReactNode}){
 const pathname=usePathname();const[playing,setPlaying]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const ctx=useRef<AudioContext|null>(null);const source=useRef<AudioBufferSourceNode|null>(null);const buffer=useRef<AudioBuffer|null>(null);const gain=useRef<GainNode|null>(null);const turning=useRef(false);
 useEffect(()=>()=>{source.current?.stop();source.current=null;void ctx.current?.close();ctx.current=null},[]);
 useEffect(()=>{const onScroll=()=>{const h=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--page-progress',String(h>0?scrollY/h:0))};window.addEventListener('scroll',onScroll,{passive:true});onScroll();return()=>window.removeEventListener('scroll',onScroll)},[pathname]);
 async function start(){if(turning.current)return;turning.current=true;setError('');setLoading(true);try{const AudioCtor=window.AudioContext;if(!AudioCtor)throw Error('Unsupported audio');if(!ctx.current){ctx.current=new AudioCtor();gain.current=ctx.current.createGain();gain.current.gain.value=.7;gain.current.connect(ctx.current.destination)}await ctx.current.resume();if(!buffer.current){const response=await fetch('/audio/arclite-loop.mp3');if(!response.ok)throw Error('Audio unavailable');buffer.current=await ctx.current.decodeAudioData(await response.arrayBuffer())}if(!source.current){source.current=ctx.current.createBufferSource();source.current.buffer=buffer.current;source.current.loop=true;source.current.connect(gain.current!);source.current.start()}setPlaying(true)}catch{setError('Sound could not start. Tap to retry.');setPlaying(false)}finally{setLoading(false);turning.current=false}}
 const cue=useCallback((kind:'select'|'settle')=>{const audio=ctx.current;if(!playing||audio?.state!=='running')return;const tone=audio.createOscillator();const envelope=audio.createGain();tone.type='sine';tone.frequency.setValueAtTime(kind==='settle'?660:440,audio.currentTime);tone.frequency.exponentialRampToValueAtTime(kind==='settle'?880:330,audio.currentTime+.12);envelope.gain.setValueAtTime(.0001,audio.currentTime);envelope.gain.exponentialRampToValueAtTime(.024,audio.currentTime+.012);envelope.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.18);tone.connect(envelope);envelope.connect(audio.destination);tone.start();tone.stop(audio.currentTime+.2);tone.onended=()=>{tone.disconnect();envelope.disconnect()}},[playing]);
 async function toggle(){if(playing){await ctx.current?.suspend();setPlaying(false)}else await start()}
 return <SoundContext.Provider value={{playing,toggle:()=>void toggle(),start,cue}}>{children}<div className="reading-progress" aria-hidden="true"/><button className={'sound-control '+(playing?'is-playing':'')} onClick={()=>void toggle()} aria-label={playing?'Mute soundtrack':'Play looping soundtrack'} aria-pressed={playing} title={playing?'Sound on — click to mute':'Sound off — click to listen'} disabled={loading}><span className="sound-bars" aria-hidden="true">{[0,1,2,3].map(n=><i key={n}/>)}</span><span className="sound-label">{loading?'LOADING':playing?'SOUND ON':'SOUND OFF'}</span></button>{error&&<p className="sound-error" role="status">{error}</p>}</SoundContext.Provider>
}
