// A withdrawal, settled on chain, through the code the dashboard button runs.
//
//   derive a vault -> shield a note -> read the tree -> build the witness -> prove -> unshield
//
// Everything up to the proof is the browser's own code path: `deriveVaultKeys`,
// `candidateNote`, `scanLeaves` and `buildUnshieldWitness` are the same functions the vault
// worker calls. The proof is generated by the `bb` CLI rather than bb.js, because proving hangs
// under Bun — and the browser prover was verified separately to produce a byte-identical shape
// (7616 bytes, 8 public inputs) on the live site.
//
// What this adds over that check is everything after the proof: whether the deployed pool
// accepts it, pays the tokens out, marks the nullifier, and splices the change note into the
// tree where the vault can find it again.
//
//   bun scripts/withdraw-e2e.mjs
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { createPublicClient, createWalletClient, http, toHex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { rhcTestnet, ARCLITE } from "../src/lib/chain/chains.ts";
import { commitment } from "../src/lib/notes/note.ts";
import { candidateNote, deriveVaultKeys, scanLeaves } from "../src/lib/notes/vault.ts";
import { buildUnshieldWitness } from "../src/lib/notes/unshield.ts";
import { readLeafSet } from "../src/server/leaves.ts";

const POOL = ARCLITE[46630].pool;
const TOKEN = "0xB32011d2CB1D071a4c2897fE61Af443Cb88E3f73"; // tNVDA
const ASSET_ID = 1;
const UNIT = 10n ** 18n;
const DEPOSIT = 4n * UNIT;
const WITHDRAW = 3n * UNIT; // partial, so the change note is exercised too

let failures = 0;
const check = (name, ok, detail = "") => {
  console.log(`${ok ? "  ok  " : " FAIL "} ${name}${detail ? ` — ${detail}` : ""}`);
  if (!ok) failures++;
};

const account = privateKeyToAccount(process.env.DEPLOYER_PRIVATE_KEY);
const pub = createPublicClient({ chain: rhcTestnet, transport: http() });
const wallet = createWalletClient({ account, chain: rhcTestnet, transport: http() });
const send = async (args, attempt = 0) => {
  try {
    const receipt = await pub.waitForTransactionReceipt({ hash: await wallet.writeContract(args) });
    // The hash, always. A revert with no hash is a revert nobody can trace, and `cast run` is
    // the only thing that turns a custom-error selector into a name.
    if (receipt.status !== "success") {
      throw new Error(`${args.functionName} reverted: ${receipt.transactionHash}`);
    }
    return receipt;
  } catch (error) {
    // The production relayer shares this account on testnet and pings the heartbeat every
    // minute, so two senders on one nonce is an operational fact here rather than a venue bug.
    if (
      !/nonce too low|replacement transaction|already known/i.test(error.message ?? "") ||
      attempt >= 5
    )
      throw error;
    await new Promise((r) => setTimeout(r, 2_000 * (attempt + 1)));
    return send(args, attempt + 1);
  }
};

const poolAbi = [
  {
    type: "function",
    name: "shield",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint16" },
      { type: "uint128" },
      { type: "bytes32" },
      { type: "bytes" },
      { type: "bytes32[]" },
      { type: "bytes" },
    ],
    outputs: [{ type: "uint32" }],
  },
  {
    type: "function",
    name: "unshield",
    stateMutability: "nonpayable",
    inputs: [
      {
        type: "tuple",
        components: [
          { name: "proof", type: "bytes" },
          { name: "root", type: "bytes32" },
          { name: "nullifier", type: "bytes32" },
          { name: "changeCommitment", type: "bytes32" },
          { name: "assetId", type: "uint16" },
          { name: "units", type: "uint128" },
          { name: "recipient", type: "address" },
          { name: "relayerFeeUnits", type: "uint128" },
          { name: "relayer", type: "address" },
          { name: "ciphertext", type: "bytes" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "openWindowId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint64" }],
  },
  {
    type: "function",
    name: "voidWindow",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "nullifierSpent",
    stateMutability: "view",
    inputs: [{ type: "bytes32" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "totalUnits",
    stateMutability: "view",
    inputs: [{ type: "uint16" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "isSolvent",
    stateMutability: "view",
    inputs: [{ type: "uint16" }],
    outputs: [{ type: "bool" }, { type: "uint256" }, { type: "uint256" }],
  },
];
const tokenAbi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [{ type: "address" }, { type: "uint256" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "mint",
    stateMutability: "nonpayable",
    inputs: [{ type: "address" }, { type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint256" }],
  },
];

// ---------------------------------------------------------------------------------------
// 1. a vault, and a note in the pool
// ---------------------------------------------------------------------------------------
console.log(`=== 1. shielding into ${POOL} ===`);

const open = await pub.readContract({ address: POOL, abi: poolAbi, functionName: "openWindowId" });
if (open !== 0n) {
  console.log(`  window ${open} is open on chain; voiding it so the deposit enters the tree`);
  await send({ address: POOL, abi: poolAbi, functionName: "voidWindow", args: [open] });
}

// A throwaway vault, derived exactly as the browser derives one. The counter is mixed with the
// clock so a rerun never produces a commitment identical to the last run's — which would be
// found at the earlier leaf and spend a note this run did not deposit.
const keys = await deriveVaultKeys(`0x${"cd".repeat(65)}`);
const counter = Number(BigInt(Date.now()) % 1_000_000n);
const note = candidateNote(keys, 1, counter, BigInt(ASSET_ID), DEPOSIT);
console.log(`  vault ${keys.fingerprint}, note counter ${counter}`);

await send({
  address: TOKEN,
  abi: tokenAbi,
  functionName: "mint",
  args: [account.address, DEPOSIT],
});
await send({ address: TOKEN, abi: tokenAbi, functionName: "approve", args: [POOL, DEPOSIT] });
await send({
  address: POOL,
  abi: poolAbi,
  functionName: "shield",
  args: [ASSET_ID, DEPOSIT, toHex(note.commitment, { size: 32 }), "0x", [], "0x"],
});

const leaves = await readLeafSet(pub, POOL, BigInt(ARCLITE[46630].deployBlock));
const found = scanLeaves([note], leaves);
check(
  "the deposit reached the tree",
  found.confirmed.length === 1,
  found.confirmed[0] ? `leaf ${found.confirmed[0].leafIndex}` : "not found",
);
if (found.confirmed.length === 0) process.exit(1);

// ---------------------------------------------------------------------------------------
// 2. the witness, from the browser's own code
// ---------------------------------------------------------------------------------------
console.log("\n=== 2. building the withdrawal witness ===");
const recipient = "0x000000000000000000000000000000000000bEEF";
const witness = buildUnshieldWitness(keys, found.root, {
  note: found.confirmed[0],
  units: WITHDRAW,
  recipient,
  changeCounter: counter + 1,
});
check(
  "a change note is derived for the remainder",
  witness.change?.units === DEPOSIT - WITHDRAW,
  `${witness.change?.units} units`,
);

// The vault has to be able to find the change note again from (epoch, counter) alone, which is
// all a recovering client holds. If it cannot, the units are in the pool with nothing able to
// point at them — indistinguishable from lost.
const regenerated = candidateNote(keys, 1, counter + 1, BigInt(ASSET_ID), DEPOSIT - WITHDRAW);
check(
  "the change note regenerates from its counter alone",
  regenerated.commitment === witness.change?.commitment,
);

// ---------------------------------------------------------------------------------------
// 3. prove
// ---------------------------------------------------------------------------------------
console.log("\n=== 3. proving ===");
const q = (v) => `"${v}"`;
writeFileSync(
  "circuits/unshield/Prover.toml",
  Object.entries(witness.inputs)
    .map(([k, v]) => (Array.isArray(v) ? `${k} = [${v.map(q).join(", ")}]` : `${k} = ${q(v)}`))
    .join("\n") + "\n",
);
const env = {
  ...process.env,
  PATH: `${process.env.HOME}/.nargo/bin:${process.env.HOME}/.bb:${process.env.PATH}`,
};
const run = (cmd, args) =>
  execFileSync(cmd, args, { cwd: "circuits", env, stdio: ["ignore", "pipe", "pipe"] });
const started = Date.now();
run("nargo", ["execute", "--package", "unshield", "withdraw_live"]);
run("bb", [
  "prove",
  "-b",
  "target/unshield.json",
  "-w",
  "target/withdraw_live.gz",
  "-o",
  "target/unshield",
  "--verifier_target",
  "evm",
  "--write_vk",
  "--verify",
]);
const proof = toHex(readFileSync("circuits/target/unshield/proof"));
console.log(`  proved and natively verified in ${((Date.now() - started) / 1000).toFixed(2)}s`);
// The browser produces 7616 bytes with 8 public inputs for this circuit, verified on the live
// site. A different shape here would mean the two provers have diverged.
check(
  "the proof is the shape the browser produces",
  (proof.length - 2) / 2 === 7616,
  `${(proof.length - 2) / 2} bytes`,
);

// ---------------------------------------------------------------------------------------
// 4. withdraw
// ---------------------------------------------------------------------------------------
console.log("\n=== 4. unshielding on chain ===");
const before = await pub.readContract({
  address: TOKEN,
  abi: tokenAbi,
  functionName: "balanceOf",
  args: [recipient],
});
const owedBefore = await pub.readContract({
  address: POOL,
  abi: poolAbi,
  functionName: "totalUnits",
  args: [ASSET_ID],
});

const p = witness.publicInputs;
const receipt = await send({
  address: POOL,
  abi: poolAbi,
  functionName: "unshield",
  args: [
    {
      proof,
      root: toHex(p.root, { size: 32 }),
      nullifier: toHex(p.nullifier, { size: 32 }),
      changeCommitment: toHex(p.changeCommitment, { size: 32 }),
      assetId: ASSET_ID,
      units: p.units,
      recipient,
      relayerFeeUnits: p.relayerFee,
      relayer: toHex(p.relayer, { size: 20 }),
      ciphertext: "0x",
    },
  ],
  // 8M. A 5M cap ran out on chain — `gasUsed` exactly 5,000,000 — while `cast run` replayed the
  // same transaction successfully, because it replays with a generous limit. Verification is
  // ~2.6M and the change-note insert ~1.1M more as the tree fills.
  gas: 8_000_000n,
});
console.log(`  settled: ${receipt.transactionHash} (${receipt.gasUsed} gas)`);

const after = await pub.readContract({
  address: TOKEN,
  abi: tokenAbi,
  functionName: "balanceOf",
  args: [recipient],
});
check("the recipient was paid, exactly", after - before === WITHDRAW, `${after - before} units`);

const owedAfter = await pub.readContract({
  address: POOL,
  abi: poolAbi,
  functionName: "totalUnits",
  args: [ASSET_ID],
});
check(
  "the pool's obligation fell by the same amount",
  owedBefore - owedAfter === WITHDRAW,
  `${owedBefore - owedAfter}`,
);

check(
  "the nullifier is spent, so the note cannot be withdrawn twice",
  await pub.readContract({
    address: POOL,
    abi: poolAbi,
    functionName: "nullifierSpent",
    args: [toHex(p.nullifier, { size: 32 })],
  }),
);

const [solvent] = await pub.readContract({
  address: POOL,
  abi: poolAbi,
  functionName: "isSolvent",
  args: [ASSET_ID],
});
check("the pool is still solvent", solvent);

// The change note has to be in the tree, or the remainder is unreachable.
const afterLeaves = await readLeafSet(pub, POOL, BigInt(ARCLITE[46630].deployBlock));
const change = scanLeaves([regenerated], afterLeaves);
check(
  "the change note is in the tree, findable by the vault",
  change.confirmed.length === 1,
  change.confirmed[0]
    ? `leaf ${change.confirmed[0].leafIndex}, ${change.confirmed[0].units} units`
    : "not found",
);

console.log(
  failures === 0 ? "\na withdrawal settled on chain, change note and all" : `\n${failures} failed`,
);
process.exit(failures === 0 ? 0 : 1);
