/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ProofsRouteImport } from './routes/proofs'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthNonceRouteImport } from './routes/api/auth/nonce'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'
import { Route as ApiCronOracleRouteImport } from './routes/api/cron/oracle'
import { Route as ApiCronTickRouteImport } from './routes/api/cron/tick'
import { Route as ApiMarketAssetsRouteImport } from './routes/api/market/assets'
import { Route as ApiMarketCrossingRouteImport } from './routes/api/market/crossing'
import { Route as ApiMarketDepthRouteImport } from './routes/api/market/depth'
import { Route as ApiMarketSeriesRouteImport } from './routes/api/market/series'
import { Route as ApiMarketSupplyRouteImport } from './routes/api/market/supply'
import { Route as ApiMarketWindowRouteImport } from './routes/api/market/window'
import { Route as ApiMarketWindowsRouteImport } from './routes/api/market/windows'
import { Route as ApiNotesDepositsRouteImport } from './routes/api/notes/deposits'
import { Route as ApiNotesLeavesRouteImport } from './routes/api/notes/leaves'
import { Route as ApiOrdersReceiptsRouteImport } from './routes/api/orders/receipts'
import { Route as ApiOrdersSubmitRouteImport } from './routes/api/orders/submit'
import { Route as ApiOrdersWindowKeyRouteImport } from './routes/api/orders/window-key'
import { Route as ApiPoolAssetsRouteImport } from './routes/api/pool/assets'
import { Route as ApiProofsSolvencyRouteImport } from './routes/api/proofs/solvency'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofsRoute = ProofsRouteImport.update({
  id: '/proofs',
  path: '/proofs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthNonceRoute = ApiAuthNonceRouteImport.update({
  id: '/api/auth/nonce',
  path: '/api/auth/nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronOracleRoute = ApiCronOracleRouteImport.update({
  id: '/api/cron/oracle',
  path: '/api/cron/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketAssetsRoute = ApiMarketAssetsRouteImport.update({
  id: '/api/market/assets',
  path: '/api/market/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCrossingRoute = ApiMarketCrossingRouteImport.update({
  id: '/api/market/crossing',
  path: '/api/market/crossing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketDepthRoute = ApiMarketDepthRouteImport.update({
  id: '/api/market/depth',
  path: '/api/market/depth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketSeriesRoute = ApiMarketSeriesRouteImport.update({
  id: '/api/market/series',
  path: '/api/market/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketSupplyRoute = ApiMarketSupplyRouteImport.update({
  id: '/api/market/supply',
  path: '/api/market/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketWindowRoute = ApiMarketWindowRouteImport.update({
  id: '/api/market/window',
  path: '/api/market/window',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketWindowsRoute = ApiMarketWindowsRouteImport.update({
  id: '/api/market/windows',
  path: '/api/market/windows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesDepositsRoute = ApiNotesDepositsRouteImport.update({
  id: '/api/notes/deposits',
  path: '/api/notes/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesLeavesRoute = ApiNotesLeavesRouteImport.update({
  id: '/api/notes/leaves',
  path: '/api/notes/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersReceiptsRoute = ApiOrdersReceiptsRouteImport.update({
  id: '/api/orders/receipts',
  path: '/api/orders/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersSubmitRoute = ApiOrdersSubmitRouteImport.update({
  id: '/api/orders/submit',
  path: '/api/orders/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersWindowKeyRoute = ApiOrdersWindowKeyRouteImport.update({
  id: '/api/orders/window-key',
  path: '/api/orders/window-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoolAssetsRoute = ApiPoolAssetsRouteImport.update({
  id: '/api/pool/assets',
  path: '/api/pool/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProofsSolvencyRoute = ApiProofsSolvencyRouteImport.update({
  id: '/api/proofs/solvency',
  path: '/api/proofs/solvency',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/proofs': typeof ProofsRoute
  '/protocol': typeof ProtocolRoute
  '/api/health': typeof ApiHealthRoute
  '/api/status': typeof ApiStatusRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/cron/oracle': typeof ApiCronOracleRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/market/assets': typeof ApiMarketAssetsRoute
  '/api/market/crossing': typeof ApiMarketCrossingRoute
  '/api/market/depth': typeof ApiMarketDepthRoute
  '/api/market/series': typeof ApiMarketSeriesRoute
  '/api/market/supply': typeof ApiMarketSupplyRoute
  '/api/market/window': typeof ApiMarketWindowRoute
  '/api/market/windows': typeof ApiMarketWindowsRoute
  '/api/notes/deposits': typeof ApiNotesDepositsRoute
  '/api/notes/leaves': typeof ApiNotesLeavesRoute
  '/api/orders/receipts': typeof ApiOrdersReceiptsRoute
  '/api/orders/submit': typeof ApiOrdersSubmitRoute
  '/api/orders/window-key': typeof ApiOrdersWindowKeyRoute
  '/api/pool/assets': typeof ApiPoolAssetsRoute
  '/api/proofs/solvency': typeof ApiProofsSolvencyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/proofs': typeof ProofsRoute
  '/protocol': typeof ProtocolRoute
  '/api/health': typeof ApiHealthRoute
  '/api/status': typeof ApiStatusRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/cron/oracle': typeof ApiCronOracleRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/market/assets': typeof ApiMarketAssetsRoute
  '/api/market/crossing': typeof ApiMarketCrossingRoute
  '/api/market/depth': typeof ApiMarketDepthRoute
  '/api/market/series': typeof ApiMarketSeriesRoute
  '/api/market/supply': typeof ApiMarketSupplyRoute
  '/api/market/window': typeof ApiMarketWindowRoute
  '/api/market/windows': typeof ApiMarketWindowsRoute
  '/api/notes/deposits': typeof ApiNotesDepositsRoute
  '/api/notes/leaves': typeof ApiNotesLeavesRoute
  '/api/orders/receipts': typeof ApiOrdersReceiptsRoute
  '/api/orders/submit': typeof ApiOrdersSubmitRoute
  '/api/orders/window-key': typeof ApiOrdersWindowKeyRoute
  '/api/pool/assets': typeof ApiPoolAssetsRoute
  '/api/proofs/solvency': typeof ApiProofsSolvencyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/proofs': typeof ProofsRoute
  '/protocol': typeof ProtocolRoute
  '/api/health': typeof ApiHealthRoute
  '/api/status': typeof ApiStatusRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/cron/oracle': typeof ApiCronOracleRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/market/assets': typeof ApiMarketAssetsRoute
  '/api/market/crossing': typeof ApiMarketCrossingRoute
  '/api/market/depth': typeof ApiMarketDepthRoute
  '/api/market/series': typeof ApiMarketSeriesRoute
  '/api/market/supply': typeof ApiMarketSupplyRoute
  '/api/market/window': typeof ApiMarketWindowRoute
  '/api/market/windows': typeof ApiMarketWindowsRoute
  '/api/notes/deposits': typeof ApiNotesDepositsRoute
  '/api/notes/leaves': typeof ApiNotesLeavesRoute
  '/api/orders/receipts': typeof ApiOrdersReceiptsRoute
  '/api/orders/submit': typeof ApiOrdersSubmitRoute
  '/api/orders/window-key': typeof ApiOrdersWindowKeyRoute
  '/api/pool/assets': typeof ApiPoolAssetsRoute
  '/api/proofs/solvency': typeof ApiProofsSolvencyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/docs'
    | '/proofs'
    | '/protocol'
    | '/api/health'
    | '/api/status'
    | '/api/auth/logout'
    | '/api/auth/nonce'
    | '/api/auth/session'
    | '/api/auth/verify'
    | '/api/cron/oracle'
    | '/api/cron/tick'
    | '/api/market/assets'
    | '/api/market/crossing'
    | '/api/market/depth'
    | '/api/market/series'
    | '/api/market/supply'
    | '/api/market/window'
    | '/api/market/windows'
    | '/api/notes/deposits'
    | '/api/notes/leaves'
    | '/api/orders/receipts'
    | '/api/orders/submit'
    | '/api/orders/window-key'
    | '/api/pool/assets'
    | '/api/proofs/solvency'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/docs'
    | '/proofs'
    | '/protocol'
    | '/api/health'
    | '/api/status'
    | '/api/auth/logout'
    | '/api/auth/nonce'
    | '/api/auth/session'
    | '/api/auth/verify'
    | '/api/cron/oracle'
    | '/api/cron/tick'
    | '/api/market/assets'
    | '/api/market/crossing'
    | '/api/market/depth'
    | '/api/market/series'
    | '/api/market/supply'
    | '/api/market/window'
    | '/api/market/windows'
    | '/api/notes/deposits'
    | '/api/notes/leaves'
    | '/api/orders/receipts'
    | '/api/orders/submit'
    | '/api/orders/window-key'
    | '/api/pool/assets'
    | '/api/proofs/solvency'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/dashboard'
    | '/docs'
    | '/proofs'
    | '/protocol'
    | '/api/health'
    | '/api/status'
    | '/api/auth/logout'
    | '/api/auth/nonce'
    | '/api/auth/session'
    | '/api/auth/verify'
    | '/api/cron/oracle'
    | '/api/cron/tick'
    | '/api/market/assets'
    | '/api/market/crossing'
    | '/api/market/depth'
    | '/api/market/series'
    | '/api/market/supply'
    | '/api/market/window'
    | '/api/market/windows'
    | '/api/notes/deposits'
    | '/api/notes/leaves'
    | '/api/orders/receipts'
    | '/api/orders/submit'
    | '/api/orders/window-key'
    | '/api/pool/assets'
    | '/api/proofs/solvency'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  ProofsRoute: typeof ProofsRoute
  ProtocolRoute: typeof ProtocolRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthNonceRoute: typeof ApiAuthNonceRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiCronOracleRoute: typeof ApiCronOracleRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
  ApiMarketAssetsRoute: typeof ApiMarketAssetsRoute
  ApiMarketCrossingRoute: typeof ApiMarketCrossingRoute
  ApiMarketDepthRoute: typeof ApiMarketDepthRoute
  ApiMarketSeriesRoute: typeof ApiMarketSeriesRoute
  ApiMarketSupplyRoute: typeof ApiMarketSupplyRoute
  ApiMarketWindowRoute: typeof ApiMarketWindowRoute
  ApiMarketWindowsRoute: typeof ApiMarketWindowsRoute
  ApiNotesDepositsRoute: typeof ApiNotesDepositsRoute
  ApiNotesLeavesRoute: typeof ApiNotesLeavesRoute
  ApiOrdersReceiptsRoute: typeof ApiOrdersReceiptsRoute
  ApiOrdersSubmitRoute: typeof ApiOrdersSubmitRoute
  ApiOrdersWindowKeyRoute: typeof ApiOrdersWindowKeyRoute
  ApiPoolAssetsRoute: typeof ApiPoolAssetsRoute
  ApiProofsSolvencyRoute: typeof ApiProofsSolvencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proofs': {
      id: '/proofs'
      path: '/proofs'
      fullPath: '/proofs'
      preLoaderRoute: typeof ProofsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/nonce': {
      id: '/api/auth/nonce'
      path: '/api/auth/nonce'
      fullPath: '/api/auth/nonce'
      preLoaderRoute: typeof ApiAuthNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/oracle': {
      id: '/api/cron/oracle'
      path: '/api/cron/oracle'
      fullPath: '/api/cron/oracle'
      preLoaderRoute: typeof ApiCronOracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/assets': {
      id: '/api/market/assets'
      path: '/api/market/assets'
      fullPath: '/api/market/assets'
      preLoaderRoute: typeof ApiMarketAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/crossing': {
      id: '/api/market/crossing'
      path: '/api/market/crossing'
      fullPath: '/api/market/crossing'
      preLoaderRoute: typeof ApiMarketCrossingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/depth': {
      id: '/api/market/depth'
      path: '/api/market/depth'
      fullPath: '/api/market/depth'
      preLoaderRoute: typeof ApiMarketDepthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/series': {
      id: '/api/market/series'
      path: '/api/market/series'
      fullPath: '/api/market/series'
      preLoaderRoute: typeof ApiMarketSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/supply': {
      id: '/api/market/supply'
      path: '/api/market/supply'
      fullPath: '/api/market/supply'
      preLoaderRoute: typeof ApiMarketSupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/window': {
      id: '/api/market/window'
      path: '/api/market/window'
      fullPath: '/api/market/window'
      preLoaderRoute: typeof ApiMarketWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/windows': {
      id: '/api/market/windows'
      path: '/api/market/windows'
      fullPath: '/api/market/windows'
      preLoaderRoute: typeof ApiMarketWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/deposits': {
      id: '/api/notes/deposits'
      path: '/api/notes/deposits'
      fullPath: '/api/notes/deposits'
      preLoaderRoute: typeof ApiNotesDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/leaves': {
      id: '/api/notes/leaves'
      path: '/api/notes/leaves'
      fullPath: '/api/notes/leaves'
      preLoaderRoute: typeof ApiNotesLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/receipts': {
      id: '/api/orders/receipts'
      path: '/api/orders/receipts'
      fullPath: '/api/orders/receipts'
      preLoaderRoute: typeof ApiOrdersReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/submit': {
      id: '/api/orders/submit'
      path: '/api/orders/submit'
      fullPath: '/api/orders/submit'
      preLoaderRoute: typeof ApiOrdersSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/window-key': {
      id: '/api/orders/window-key'
      path: '/api/orders/window-key'
      fullPath: '/api/orders/window-key'
      preLoaderRoute: typeof ApiOrdersWindowKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pool/assets': {
      id: '/api/pool/assets'
      path: '/api/pool/assets'
      fullPath: '/api/pool/assets'
      preLoaderRoute: typeof ApiPoolAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proofs/solvency': {
      id: '/api/proofs/solvency'
      path: '/api/proofs/solvency'
      fullPath: '/api/proofs/solvency'
      preLoaderRoute: typeof ApiProofsSolvencyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  ProofsRoute: ProofsRoute,
  ProtocolRoute: ProtocolRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthNonceRoute: ApiAuthNonceRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiCronOracleRoute: ApiCronOracleRoute,
  ApiCronTickRoute: ApiCronTickRoute,
  ApiMarketAssetsRoute: ApiMarketAssetsRoute,
  ApiMarketCrossingRoute: ApiMarketCrossingRoute,
  ApiMarketDepthRoute: ApiMarketDepthRoute,
  ApiMarketSeriesRoute: ApiMarketSeriesRoute,
  ApiMarketSupplyRoute: ApiMarketSupplyRoute,
  ApiMarketWindowRoute: ApiMarketWindowRoute,
  ApiMarketWindowsRoute: ApiMarketWindowsRoute,
  ApiNotesDepositsRoute: ApiNotesDepositsRoute,
  ApiNotesLeavesRoute: ApiNotesLeavesRoute,
  ApiOrdersReceiptsRoute: ApiOrdersReceiptsRoute,
  ApiOrdersSubmitRoute: ApiOrdersSubmitRoute,
  ApiOrdersWindowKeyRoute: ApiOrdersWindowKeyRoute,
  ApiPoolAssetsRoute: ApiPoolAssetsRoute,
  ApiProofsSolvencyRoute: ApiProofsSolvencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
